# -*- coding: utf-8 -*-
"""spamemailML.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ctL-0pBCiU3ddtb1Ria1hKnaVJ4Vng1c
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
import os
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report
from sklearn.linear_model import LogisticRegression
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.pipeline import make_pipeline
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import (accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, confusion_matrix, classification_report)
from sklearn.pipeline import Pipeline
from sklearn.model_selection import GridSearchCV

df = pd.read_csv('/content/spam_email_dataset.csv')
df.head()

df.shape

df.info

#feature selection
features=['num_words','num_links','num_exclamation_marks','sender_reputation_score','num_recipients','contains_money_terms','contains_urgency_terms']
x= df[features]
y= df['label']

x_train, x_test, y_train, y_test= train_test_split(x,y, test_size=0.2, random_state=42)

lr= LogisticRegression()
lr.fit(x_train, y_train)
pred_lr= lr.predict(x_test)
print("Lr accuracy:", accuracy_score(y_test, pred_lr))

dt= DecisionTreeClassifier()
dt.fit(x_train, y_train)
pred_dt= dt.predict(x_test)

nb= MultinomialNB()
nb.fit(x_train, y_train)
pred_nb= nb.predict(x_test)

knn= KNeighborsClassifier()
knn.fit(x_train, y_train)
pred_knn= knn.predict(x_test)

rf= RandomForestClassifier()
rf.fit(x_train, y_train)
pred_rf= rf.predict(x_test)
print("Rf accuracy:", accuracy_score(y_test, pred_rf))

print("Logistic Regression Classification Report:", classification_report(y_test, pred_lr))
print("Random Forest Classification Report:", classification_report(y_test, pred_rf))
print("Decision tree classification report: ", classification_report(y_test, pred_dt))
print("KNN classification report: ", classification_report(y_test, pred_knn))
print("Naive Bayes classification report: ", classification_report(y_test, pred_nb))

#feature importance of rf
importance= pd.Series(rf.feature_importances_,index= features)
importance.sort_values(ascending=False).plot(kind='barh')
plt.title("Feature Importance")
plt.show()

rf.fit(x_train, y_train)

from sklearn.metrics import log_loss

#classification metrics
eval_models = {
    "Logistic Regression": lr,
    "Decision Tree": dt,
    "K-Nearest Neighbors": knn,
    "Random Forest": rf,
    "Naive Bayes": nb
}

metric_results = {}

for name, model in eval_models.items():
    y_pred = model.predict(x_test)
    y_prob = model.predict_proba(x_test)[:, 1]

    metric_results[name] = {"y_pred": y_pred, "y_prob": y_prob}


    print(f"  {name}")
    print(f"  Accuracy        : {accuracy_score(y_test, y_pred):.4f}")
    print(f"  Precision       : {precision_score(y_test, y_pred):.4f}")
    print(f"  Recall          : {recall_score(y_test, y_pred):.4f}")
    print(f"  F1-Score        : {f1_score(y_test, y_pred):.4f}")
    print(f"  ROC-AUC         : {roc_auc_score(y_test, y_prob):.4f}")
    print(f"  Log Loss        : {log_loss(y_test, y_prob):.4f}")

from sklearn.metrics import mean_squared_error, mean_absolute_error, brier_score_loss
#regression metrics
for name, res in metric_results.items():
    y_prob = res["y_prob"]
    mse    = mean_squared_error(y_test, y_prob)
    rmse   = np.sqrt(mse)
    mae    = mean_absolute_error(y_test, y_prob)
    brier  = brier_score_loss(y_test, y_prob)

    print(f"\n  {name}")
    print(f"  MSE          : {mse:.4f}   ← avg squared error of prob vs true label")
    print(f"  RMSE         : {rmse:.4f}  ← same scale as probability (0–1)")
    print(f"  MAE          : {mae:.4f}   ← avg absolute error of prob vs true label")
    print(f"  Brier Score  : {brier:.4f} ← primary calibration metric (lower = better)")

from sklearn.metrics import roc_curve, auc
plt.figure(figsize=(8, 5))
for name, res in metric_results.items():
    fpr_c, tpr_c, _ = roc_curve(y_test, res["y_prob"])
    roc_auc_val      = auc(fpr_c, tpr_c)
    plt.plot(fpr_c, tpr_c, label=f"{name} (AUC = {roc_auc_val:.3f})")
plt.plot([0, 1], [0, 1], 'k--', label='Baseline')
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve")
plt.legend()
plt.savefig("roc_curve.png", dpi=150)
plt.show(

)

for name, res in metric_results.items():
    y_pred = res["y_pred"]
    tn, fp, fn, tp = confusion_matrix(y_test, y_pred).ravel()

    specificity  = tn / (tn + fp)
    fpr_val      = fp / (fp + tn)
    fnr_val      = fn / (fn + tp)
    balanced_acc = (recall_score(y_test, y_pred) + specificity) / 2

    print(f"\n  {name}")
    print(f"  TP (Spam caught)          : {tp}")
    print(f"  TN (Ham correctly passed) : {tn}")
    print(f"  FP (Ham flagged as spam)  : {fp}")
    print(f"  FN (Spam missed)          : {fn}")
    print(f"  Specificity               : {specificity:.4f}")
    print(f"  False Positive Rate       : {fpr_val:.4f}")
    print(f"  False Negative Rate       : {fnr_val:.4f}")
    print(f"  Balanced Accuracy         : {balanced_acc:.4f}")

fig, axes = plt.subplots(1, 2, figsize=(12, 4))
for ax, (name, res) in zip(axes, metric_results.items()):
    cm = confusion_matrix(y_test, res["y_pred"])
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', ax=ax,
                xticklabels=['Ham', 'Spam'],
                yticklabels=['Ham', 'Spam'])
    ax.set_title(f"{name} — Confusion Matrix")
    ax.set_xlabel("Predicted")
    ax.set_ylabel("Actual")
plt.tight_layout()
plt.savefig("confusion_matrices.png", dpi=150)
plt.show()

from sklearn.metrics import matthews_corrcoef

# Prepare data for summary_df
summary_data = {}
for name, res in metric_results.items():
    y_pred = res["y_pred"]
    y_prob = res["y_prob"]
    summary_data[name] = {
        "Accuracy": accuracy_score(y_test, y_pred),
        "Precision": precision_score(y_test, y_pred),
        "Recall": recall_score(y_test, y_pred),
        "F1": f1_score(y_test, y_pred),
        "ROC-AUC": roc_auc_score(y_test, y_prob),
        "MCC": matthews_corrcoef(y_test, y_pred)
    }

# Create summary_df
summary_df = pd.DataFrame.from_dict(summary_data, orient='index')

metrics_to_plot = ["Accuracy", "Precision", "Recall", "F1", "ROC-AUC", "MCC"]
summary_df[metrics_to_plot].T.plot(
    kind='bar', figsize=(12, 5), colormap='Set2', edgecolor='black'
)
plt.title("Model Metric Comparison")
plt.ylabel("Score")
plt.xticks(rotation=45)
plt.ylim(0.7, 1.0)
plt.legend(title="Model")
plt.tight_layout()
plt.savefig("metric_comparison.png", dpi=150)
plt.show()